repos:
  - repo: local
    hooks:
      - id: trufflehog-check
        name: trufflehog check
        description: Detect secrets
        entry: bash -c "trufflehog git file://. --since-commit HEAD --no-verification --fail --no-update"
        language: system
        stages: ["pre-commit", "pre-push"]
